query WeatherForecast($input: CoordinateInput!) {
  weatherForecast(input: $input) {
    date
    sunrise
    sunset
    temperature
    feelsLike
    weather {
      main
      description
    }
    daily {
      date
      pressure
      humidity
      temperature {
        day
        min
        max
        night
        evening
        morning
      }
      feelsLike {
        day
        night
        evening
        morning
      }
    }
  }
}
